// Generated by gencpp from file vision/BlobDetection.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_BLOBDETECTION_H
#define VISION_MESSAGE_BLOBDETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/ColorRGBA.h>
#include <std_msgs/Float64.h>
#include <geometry_msgs/Point.h>

namespace vision
{
template <class ContainerAllocator>
struct BlobDetection_
{
  typedef BlobDetection_<ContainerAllocator> Type;

  BlobDetection_()
    : header()
    , colors()
    , sizes()
    , locations()  {
    }
  BlobDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , colors(_alloc)
    , sizes(_alloc)
    , locations(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::std_msgs::ColorRGBA_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::ColorRGBA_<ContainerAllocator> >::other >  _colors_type;
  _colors_type colors;

   typedef std::vector< ::std_msgs::Float64_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::Float64_<ContainerAllocator> >::other >  _sizes_type;
  _sizes_type sizes;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _locations_type;
  _locations_type locations;




  typedef boost::shared_ptr< ::vision::BlobDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::BlobDetection_<ContainerAllocator> const> ConstPtr;

}; // struct BlobDetection_

typedef ::vision::BlobDetection_<std::allocator<void> > BlobDetection;

typedef boost::shared_ptr< ::vision::BlobDetection > BlobDetectionPtr;
typedef boost::shared_ptr< ::vision::BlobDetection const> BlobDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::BlobDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::BlobDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'vision': ['/home/racecar/racecar-ws/src/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::BlobDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::BlobDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::BlobDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::BlobDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::BlobDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::BlobDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::BlobDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4757db88dec50fec01a1ad0746758859";
  }

  static const char* value(const ::vision::BlobDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4757db88dec50fecULL;
  static const uint64_t static_value2 = 0x01a1ad0746758859ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::BlobDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/BlobDetection";
  }

  static const char* value(const ::vision::BlobDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::BlobDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
std_msgs/ColorRGBA[] colors\n\
std_msgs/Float64[] sizes\n\
geometry_msgs/Point[] locations\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/ColorRGBA\n\
float32 r\n\
float32 g\n\
float32 b\n\
float32 a\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::vision::BlobDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::BlobDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.colors);
      stream.next(m.sizes);
      stream.next(m.locations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlobDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::BlobDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::BlobDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "colors[]" << std::endl;
    for (size_t i = 0; i < v.colors.size(); ++i)
    {
      s << indent << "  colors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "    ", v.colors[i]);
    }
    s << indent << "sizes[]" << std::endl;
    for (size_t i = 0; i < v.sizes.size(); ++i)
    {
      s << indent << "  sizes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "    ", v.sizes[i]);
    }
    s << indent << "locations[]" << std::endl;
    for (size_t i = 0; i < v.locations.size(); ++i)
    {
      s << indent << "  locations[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.locations[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_BLOBDETECTION_H
